language: node_js
sudo: required
script:
  - ./_scripts/run-tests.sh
# Keep Travis from testing `master` branch
branches:
  except:
  - master
node_js:
 - '6.1'
env:
  global:
  - secure: uTfseht9fdu66o5h+hoAjH/TkJo7+5JBiOP67OI/JY363bgePJEhLsFhkXQnaxryKLz+GHEcrihy6NNkXgunLUIW8I4feYAj1rYRVU/I5oLXAXaP5Cxasu+zJWH4vqSCX9HzZ3CYxVE4TzSIFh1XLs2YElg6LNoMSywnd7JyFivfC61u5A8JnAC9tunVhjoyoHz+to6IjJ7XKR1Lh6bWMCVWrs2fIfa1WEv237XUHAj+4UFbZcwsxnRBdSTnDh/MCZvC9pQpEbZXmiWUKNEmsELysxqQUc9N6gA3Rm2SBKXwxeyeINrtoErM1Y0UJUArAOIyHqWgE+qWvZtgTKvwP6sf/ASnt1YToDI/XZ8VDUgEpPq0qwZWc9SsBk26L44tCLiV9pdAIEcwTdaWlYItkvQ9XbqM8/LfQcTUUpRSUIqfAZcRNzUI+M1NsbvuTdWDpvwCYZAFtsgrpcwYkKenRc7vjU3gNdAY328JoNbGSf0Uy+gGo5LBDx/BAZ9oR960vYykFcyou7gezTqMay1KckeokIiOpexPJv3dd+xYtWE+4k/HJyWl+Wt/6MtLAp2089tp+C4MjQnsBDeksl9K8TSML7raC0IR8RXefc4WrbWIYxYhFUQHTbhC1uKox+cxxZvsm3QuIRP3PKrLGFdPDb4OXN2+lbNZQkMp44Pqezc=
  - secure: NYzrZmOIHlwCOFNhG9qb94oC/kmMaCx/TPiwFlpSeeyuH3GtEfNDOBW9oLUO15xfkACGCTDUalB8aDJedISUs2YWrKp1B6GlHLeQxo8z1f9MrE7LKFhHGs4L6AcJ8KTNUi0GKVxRHjuWnHogWALPDZolGKYJWJXXAjiLz3HEtGuwRcscmJ4GMXH7k1GD8iOhcFvKNQfxnsboeCH/+HCgIY0uH9PFg+PIzniDChtTcou/vgRu5pXRCuFurIsMhCZBFZtCZYO6CizTqLnvIre4EDjbP9pHm8UV6HroXCc6ZKH0ef9izL43WFTzYdPZGgTgM/7+7LXzKFlTj6dKEs7RagdTbfRJm8o36ra5IdyI0Mn8bTGqPgEqmJiPm2WhSqIC7urCOthGcprJI7a9GKV5+xfCad3sw1NFKRlJikIk2NdKcDqxiAzqIaVhss8xAJ/SyQnnlKXX1s8ySIKqaiipTFeVJQ39ushBWWMtTkDD63+P2iZ0F0dCNCZzkhdNiYU6RNTUYOkE6NrDNQVhcLRNZEpXGGBS9DWJgoElg7ttFCsN9gpB0eb61VBeaRPTYWYgPqI1b+xFnCXXZ/SsdU5edqFbx2g1gQW9I1Yw+A1fY14VEgv5FeAt2tOC5lCaVXg7MmY+UCBGzOFJk1icI8ZjzcoxsrvaIIXayCNwjpLxnM0=

# Deployment config
deploy:
  provider: script
  script: "./build.sh"
  skip_cleanup: false
  on:
    branch: redesign
