language: node_js
sudo: required
branches:
  except:
  - master
node_js:
- '6.1'
env:
  global:
  - secure: xEv16/16AGMwK5BiEthtkhXkZe9bp2hw7jCXBs1gHjAl2yNf8kAQq8k2wqyBftOEJV1RPx3pF8RmdRSDQlI/47EsBSV6q+R7my9bp9SnNALh8EkyAFKSBYgQ631MC/a0gRxyZ92SDMlBwAKQBtJ/GvDLPm+gSjw5zMxBb1gJsCMuUH+7MZDjZ0Ec1XY00I9S6bXL5drfd1Tf5QMYiUUGQQWQu46zDhqPte1Hy9kQ2YDNuy0yGa91bI+YN5v6M1tmj1WQ3FCsU7HyzfF1XPm+fTY0fmKTRBGMXY5VN58cstm5IbD/1fEluFetzfKoHs7195voGZe6YKdT3UHEwCeExH2Swg4xOhQs5fhZoBEkOBl+EinRw84pTYaXPJBuyF0u9LtT3DxF/ZpfTt2ODxvq6ZsG1JewtWEbFn2Nbte8PN6zBpKp5CXNBWy7ne8pPsNitHSBeT/cLmDAkz02ERiz+rK4Wdl02qBROsIWJmaVdL7LRa2SKEDE4E8FL8wEFLQpCrgPySNAl16MRaLOwJ0zsy7aWx0wObCUeOqAp3NrP0Xv01jK3TKtqIVByMgj9UyQ8rR72xqyPPbtaTnB2GHMFFdVowVm2EJbRlHHr6v+Ioh0aq0MJjKI/Af9alKTNiBr7nC81pT1+qf52uS5HD/LDP/j5XQWelOGkHaIvy1ODSY=
  - secure: fQaM4bywhlrV3rl3pTFZLQISJDFCLZrTKAgNu069jYKeY72yoOB4HAJPJAajp66Kgi2RCaQs3e2+KeRKJ9Bd2to7lV5yCV2fAZMN/lIonb9SW7MvMhEgkx4nxWBzPtiyMrLGY8MOt2d+SKDHq1DoXgBkQaj4vvSqVOf+TM/8eZH4HzbCaGc+iUOr8ZbO8oaWJMC9txtl5Xng8UFytoPcCQI57KJ9zckoYOLF/PhSgJaNE0isSkh4J/Za+6dFRvBhQVJVZV/5x791nDXubwfaqnwLAdf43/bg0v8yFxTcIMxjGxf89ZC7GxNngxJv0lLskEAozgaG3ewJz5qrJck8hp7R/LZ/y2gFgr3suvLQa/KIAlPmmMxkQ9A9jbGa786GLJkbQQzJpZW5IriOZ0Ial0OBPL8dZECw/V1Wb2B7fOjtIAx+DAzBH1G+nXQhPCFbnnCD+Sxpsp2RdZbs2gUr5DxnYZI/qEnWVDUUukFsTE7cHdkWfCfgKG9cSwqERXVWCGfyUEOuqmzF8TSQ71YrSXePxO9vQa9SkAyws/Zzv7zO+02SrNoMQq8kqjfzPGcO4IhIPKlkCB88BQeei5HSRsLOM9zt/ATbtNwTYkOdRD9trBjR1QP4HaVgCEJFcqBZGo4J7FA0B7rn2k4mM3prtxi4+FriDSrM+5j8gTUIgo8=
deploy:
  provider: script
  script: "./build.sh"
  skip_cleanup: false
  on:
    branch: redesign
