# Site settings
title: Conspiracy of Shadows
email: keith.senkowski@gmail.com
description: > #Hi, my name is Keith Senkowski and I am an illustrator, author, technologist and game designer. For over ten years I have been working on a project called Conspiracy of Shadows. It began as a tabletop role-playing game (RPG) and eventually evolved into a multi-faceted art project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://conspiracyofshadows.com.com" # the base hostname & protocol for your site
twitter_username: ksenkowski
github_username:  ksenkowski

# Build settings
markdown: kramdown
permalink: /:categories/:title.html

sass:
  sass_dir: _sass
  style: :compressed