# Site settings
title: Conspiracy of Shadows
email: keith.senkowski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://conspiracyofshadows.com.com" # the base hostname & protocol for your site
twitter_username: ksenkowski
github_username:  ksenkowski

# Build settings
markdown: kramdown
permalink: /:categories/:title.html

sass:
  sass_dir: _sass
  style: :compressed